apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-keycloak-new
  namespace: rhdh-operator
spec:
  hostname:
    hostname: keycloak-rhdh-operator.apps.cluster-nkmjp.dynamic.redhatworkshops.io
  http:
    httpEnabled: true
    httpPort: 8090
    tlsSecret: my-tls-secret
  httpManagement:
    port: 8080
  instances: 1
