apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: rhdh-realm
  namespace: rhdh-operator
spec:
  keycloakCRName: example-keycloak-new
  realm:
    id: rhdh
    realm: rhdh
    enabled: true
    displayName: "RHDH Realm"
    clients:
      - clientId: developer-hub
        secret: devhub-secret
        enabled: true
        protocol: openid-connect
        publicClient: false
        redirectUris:
          - "https://rhdh.apps.cluster-nkmjp.dynamic.redhatworkshops.io/auth/oidc/handler/frame"
        baseUrl: "https://rhdh.apps.cluster-nkmjp.dynamic.redhatworkshops.io"
        adminUrl: "https://rhdh.apps.cluster-nkmjp.dynamic.redhatworkshops.io"
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: true
        authorizationServicesEnabled: true
