apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: rhdh-realm
  namespace: rhdh-operator
spec:
  keycloakCRName: example-keycloak-new
  realm:
    id: rhdh
    realm: rhdh
    enabled: true
    displayName: "Red Hat Developer Hub Realm"
    loginWithEmailAllowed: true
    registrationAllowed: false
    resetPasswordAllowed: true
    editUsernameAllowed: false
