---
apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
  namespace: rhdh-operator
  labels:
    app.kubernetes.io/name: backstage
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src
    extraEnvs:
      envs:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              name: rhdh-vars
              key: BASE_URL
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: rhdh-vars
              key: CORS_ORIGIN
      secrets:
        - name: rhdh-secrets
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
      host: rhdh.apps.cluster-nkmjp.dynamic.redhatworkshops.io
      subdomain: apps.cluster-nkmjp.dynamic.redhatworkshops.io
  database:
    enableLocalDb: true
...
