apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhdh.rhdh-operator: ''
  name: rhdh
  namespace: rhdh-operator
  creationTimestamp: '2025-04-03T17:14:26Z'
spec:
  channel: fast
  installPlanApproval: Automatic
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhdh-operator.v1.5.1
status:
  installplan:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-jggqf
  installedCSV: rhdh-operator.v1.5.1
  currentCSV: rhdh-operator.v1.5.1
  installPlanRef:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-jggqf
    namespace: rhdh-operator
