apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rhdh/1-namespace.yaml
  - rhdh/2-OperatorGroup.yaml
  - rhdh/3-Subscription.yaml
  - rhdh/4-Secret.yaml
  - rhdh/rhdh-vars.yaml
  - rhdh/6-backstage.yaml

configMapGenerator:
  - name: app-config-rhdh
    namespace: rhdh-operator
    behavior: create
    files:
      - rhdh/app-config-rhdh.yaml

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: rhdh-vars
      namespace: rhdh-operator
      fieldPath: data.BASE_URL
    targets:
      - select:
          kind: Backstage
          name: developer-hub
        fieldPaths:
          - spec.application.route.host
