apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhdh
  namespace: rhdh-operator
spec:
  channel: fast
  name: rhdh-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
