apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redhat-devhub
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rhdh-keycloak
    repoURL: https://github.com/YogiSoni-lazy/devhub-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - CreateNamespace=true
