# keycloak-access-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-keycloak-access
  namespace: rhdh-operator
rules:
  - apiGroups: ["k8s.keycloak.org"]
    resources: ["keycloaks"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-keycloak-access-binding
  namespace: rhdh-operator
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: argocd-keycloak-access
  apiGroup: rbac.authorization.k8s.io
